### PR TITLE
fix: load config on macOS

### LINKED ISSUE #3: Config dir on macOS
> Minimal configuration. Need to be at ~/.config/algia/config.json

On macOS this actually defaults to `$HOME/Library/Application Support/algia/config.json` as per [os.UserConfigDir](https://pkg.go.dev/os#UserConfigDir), which is not ideal.

I think the most straightforward way to get macOS clients to use the `~/.config` dir is to replace `os.UserConfigDir` with a 3rd party package like `github.com/mitchellh/go-homedir`. If this is an acceptable solution let me know - I'd be happy to submit a pull request.

### PR DESCRIPTION
**Pull request by bndw**
On macOS, `os.UserConfigDir` returns `$HOME/Library/Application Support` and not `~/.config`. This patch uses a module that works across OSes.

Fixes #3

### CODE REVIEW

**Comment by mattn** [comment]
If you have problems on macOS, please apply the code only on macOS. This change will break Windows.

**Comment by bndw** [comment]
Good catch. I've moved the macOS-specific change to only target macOS, and made the original code not target macOS.

Let me know if you prefer a different implementation approach. I don't love how this splits the Config stuff into multiple files but I wasn't sure of a better way to do it. I can also refactor `loadConfig` a bit so there's not as much duplication.

File: load_config.go [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+	"encoding/json"
+	"fmt"
+	"io/ioutil"
+	"os"
+	"path/filepath"
+	"strings"
+)
+
+func loadConfig(profile string) (*Config, error) {
+	dir, err := os.UserConfigDir()
```
Comment (junkpiano) [inline load_config.go]: Hi there,

Allow me to jump in.
Does it also make sense to create a function to return the config directory?

```
func configDir() (string, error) (
    if runtime.GOOS == "darwin" {
        return os.UserHomeDir()
    }

    return os.UserConfigDir()
}
```

Then we don't need separate files per platform.

Comment (bndw) [reply load_config.go]: Great call, updated.

Comment (mattn) [reply load_config.go]: homedir is not required at least?

Comment (bndw) [reply load_config.go]: `homedir` or similar is required for macOS - the example code above is copypasta and doesn't actually work as is.

Again, `os.UserHomeDir()` returns `$HOME/Library/Application Support` and not `~/` on macOS.

Comment (junkpiano) [reply load_config.go]: Hmm, it's strange. On my mac machine, `os.UserHomeDir()` returns the same value as `$HOME`.
I am on go `1.20`.

Comment (bndw) [reply load_config.go]: Sorry, I misread `os.UserHomeDir` for `os.UserConfigDir`. The latter is what algia uses today and causes the problem, but you're totally correct that `os.UserHomeDir` returns the homedir on macOS.

Updated the PR again to only use package `os`.

**Comment by mattn** [comment]
thank you
